// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1v7aSIgtO77j113kTq6VmimutkLbSHx0',
    appId: '1:599455104901:web:0d97f0b7c8e5ed95740eec',
    messagingSenderId: '599455104901',
    projectId: 'fir-auth-demo-61160',
    authDomain: 'fir-auth-demo-61160.firebaseapp.com',
    storageBucket: 'fir-auth-demo-61160.appspot.com',
    measurementId: 'G-CEWWQ6T4R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHgWry-kpwLAt262qfF-fGIk5Trwsr33Y',
    appId: '1:599455104901:android:6a88414fb0f1f749740eec',
    messagingSenderId: '599455104901',
    projectId: 'fir-auth-demo-61160',
    storageBucket: 'fir-auth-demo-61160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4j7SlkKgMG57zX1W12-rm7Lt3pF-LOIY',
    appId: '1:599455104901:ios:6b5cfad7b2788bde740eec',
    messagingSenderId: '599455104901',
    projectId: 'fir-auth-demo-61160',
    storageBucket: 'fir-auth-demo-61160.appspot.com',
    iosClientId: '599455104901-g873r0iqa23behp4416nuuqhttv0mc18.apps.googleusercontent.com',
    iosBundleId: 'com.github.AndrewAlbizati.authenticationDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4j7SlkKgMG57zX1W12-rm7Lt3pF-LOIY',
    appId: '1:599455104901:ios:6b5cfad7b2788bde740eec',
    messagingSenderId: '599455104901',
    projectId: 'fir-auth-demo-61160',
    storageBucket: 'fir-auth-demo-61160.appspot.com',
    iosClientId: '599455104901-g873r0iqa23behp4416nuuqhttv0mc18.apps.googleusercontent.com',
    iosBundleId: 'com.github.AndrewAlbizati.authenticationDemo',
  );
}
